version: "3"
services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: unlisted
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: waterquality
    ports:
      - "3306:3306"
    networks:
      - "website"
      - "backend"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: unlisted
      MYSQL_PASSWORD: 123456
    networks:
      - backend

networks:
  website:
  backend:
