CREATE TABLE IF NOT EXISTS ph (
    id_data INT AUTO_INCREMENT PRIMARY KEY,
    waktu TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    nilai FLOAT
);

CREATE TABLE IF NOT EXISTS kekeruhan (
    id_data INT AUTO_INCREMENT PRIMARY KEY,
    waktu TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    nilai INT
)